name = "domain-check"
main = "src/index.js"
compatibility_date = "2025-11-17"
keep_vars = true

[[kv_namespaces]]
binding = "DOMAIN_KV" 
id = "ac51a1e2132546a99d6e5a44c27f8792" # action部署时被变量替换

[triggers]
crons = ["0 */12 * * *"] # action部署时被变量替换，默认为北京时间 9:00 和 21:00
